"""MCP Apps scaffold for Markdown Vault MCP.

Demonstrates the fastmcp >=3.2.4 app-tool addressing pattern:

- Hash injection via ``hash_tool`` / ``hashed_backend_name`` from
  ``fastmcp.server.providers.addressing``.
- ``_rewrite_spa_app_tool_calls``: validates and rewrites
  ``app___<tool>`` source literals in the SPA HTML to the
  ``<hex_hash>_<tool>`` wire form at module import.
- ``_APP_TOOL_NAMES``: single source of truth for app-only tool names;
  three-way validation rejects drift between the set, the HTML, and the
  registration sites.

Replace the placeholder tools and HTML with your domain's implementation.
See ``register_apps`` for the tool registration pattern (``DOMAIN-APP-TOOLS``),
the ``DOMAIN-APP-RESOURCE`` block to configure the app-shell resource's
``AppConfig`` (e.g. sandbox ``domain`` + ``csp`` for a UI loaded in a client's
sandboxed iframe), and ``_SPA_SHELL_HTML`` (loaded from ``static/app.html``,
generated by ``scripts/vendor_spa.py`` from ``static/app.src.html``).
"""

from __future__ import annotations

import asyncio
import importlib.resources
import logging
import os
import re
from dataclasses import asdict
from typing import Any, Literal

from fastmcp import FastMCP
from fastmcp.dependencies import Depends

try:
    from fastmcp.apps import AppConfig, ResourceCSP
    from fastmcp.server.providers.addressing import (
        hash_tool,
        hashed_backend_name,
    )
except ImportError as exc:  # pragma: no cover
    raise ImportError(
        "fastmcp.apps and fastmcp.server.providers.addressing are required "
        "for MCP Apps SPA tool routing. Pin fastmcp>=3.2.4 in pyproject.toml."
    ) from exc

from markdown_vault_mcp.config import _ENV_PREFIX
from markdown_vault_mcp.vault import Vault

from ._icons import _TOOL_ICONS
from ._vault_apps import (
    _CDN_RESOURCE_DOMAINS,
    _compute_claude_app_domain,
    _graph_view_payload,
)
from .domain import get_vault

logger = logging.getLogger(__name__)

_APP_NAME = "markdown_vault_mcp"
_APP_URI = "ui://markdown_vault_mcp/app.html"

# Single source of truth for app-only tool names.
# Three invariants are enforced automatically:
#   (1) _rewrite_spa_app_tool_calls at module import rejects HTML with zero
#       app___<name> literals.
#   (2) _rewrite_spa_app_tool_calls rejects literals not in this set.
#   (3) _rewrite_spa_app_tool_calls rejects names in this set absent from HTML.
# _app_tool_meta enforces (2) again at register_apps() call time.
# When adding a tool: add its name here AND add a matching
# app___<name> literal to the SPA HTML in static/app.src.html.
_APP_TOOL_NAMES: frozenset[str] = frozenset(
    {
        # DOMAIN-APP-TOOL-NAMES-START — add app-only tool names here; kept across copier update.
        "vault_context",
        "vault_graph_neighborhood",
        "vault_graph_hubs",
        "vault_list",
        "vault_read",
        "vault_search",
        # DOMAIN-APP-TOOL-NAMES-END
    }
)


def _app_tool_meta(tool_name: str) -> dict[str, Any]:
    """Build the per-tool ``meta`` dict for a fastmcp >=3.2.4 app-only tool."""
    if tool_name not in _APP_TOOL_NAMES:
        raise ValueError(f"Unknown app tool {tool_name!r}; add to _APP_TOOL_NAMES.")
    return {
        "fastmcp": {
            "app": _APP_NAME,
            "_tool_hash": hash_tool(_APP_NAME, tool_name),
        }
    }


def _hashed(tool_name: str) -> str:
    """Return the ``<hash>_<tool_name>`` callable name for an app-only tool."""
    return hashed_backend_name(_APP_NAME, tool_name)


def _rewrite_spa_app_tool_calls(html: str) -> str:
    """Rewrite SPA's ``app___<tool>`` literals to fastmcp's hash form.

    fastmcp 3.2.4 dropped ``<app>___<tool>`` routing; the dispatcher now
    only accepts ``<hex_hash>_<tool>`` (computed by
    :func:`fastmcp.server.providers.addressing.hashed_backend_name`).
    Substitution happens once at module import so the source HTML stays
    diff-readable while the wire form is already addressed correctly.

    Raises :class:`RuntimeError` if:

    - zero ``app___<tool>`` literals are found in the HTML;
    - the HTML references a tool name not in :data:`_APP_TOOL_NAMES`;
    - :data:`_APP_TOOL_NAMES` contains a name absent from the HTML.
    """
    captured: set[str] = set()

    def _capture(m: re.Match[str]) -> str:
        name = m.group(1)
        captured.add(name)
        return _hashed(name)

    new_html, count = re.subn(
        r"app___([a-z_][a-z0-9_]*)",
        _capture,
        html,
    )
    if count == 0:
        raise RuntimeError(
            "SPA rewrite found zero 'app___<tool>' literals — "
            "check static/app.html still uses the app___<tool> source form."
        )
    unexpected = captured - _APP_TOOL_NAMES
    if unexpected:
        raise RuntimeError(
            f"SPA references unknown tools: {sorted(unexpected)}. "
            "Fix the typo in static/app.src.html or add the name to _APP_TOOL_NAMES."
        )
    missing = _APP_TOOL_NAMES - captured
    if missing:
        raise RuntimeError(
            f"SPA doesn't reference declared tools: {sorted(missing)}. "
            "Remove from _APP_TOOL_NAMES or wire the SPA to call them."
        )
    return new_html


# SPA shell HTML — loaded from the vendored static/app.html (generated by
# scripts/vendor_spa.py).  Uses fixed app___<tool> source literals;
# _rewrite_spa_app_tool_calls rewrites them to the fastmcp >=3.2.4 hash form
# at module import.  Edit static/app.src.html (not app.html) and re-run
# scripts/vendor_spa.py.
_SPA_SHELL_HTML = _rewrite_spa_app_tool_calls(
    importlib.resources.files("markdown_vault_mcp")
    .joinpath("static/app.html")
    .read_text(encoding="utf-8")
)


def register_apps(mcp: FastMCP) -> None:
    """Register MCP Apps resource and app-only tools on *mcp*."""

    # DOMAIN-APP-RESOURCE-START — vault app-shell AppConfig: resolve Claude's
    # sandbox iframe domain (explicit APP_DOMAIN or auto-computed from BASE_URL)
    # and the CSP for vendored assets. Logged from this module so the domain is
    # visible at boot. Kept across copier update.
    app_domain: str | None = (
        os.environ.get(f"{_ENV_PREFIX}_APP_DOMAIN", "").strip()
        or _compute_claude_app_domain()
    )
    if app_domain:
        logger.info("MCP Apps domain: %s", app_domain)
    else:
        logger.debug("MCP Apps domain: not configured (stdio or no BASE_URL)")
    app_resource_config = AppConfig(
        domain=app_domain,
        csp=ResourceCSP(resource_domains=_CDN_RESOURCE_DOMAINS),
    )
    # DOMAIN-APP-RESOURCE-END

    @mcp.resource(_APP_URI, app=app_resource_config)
    def _app_shell() -> str:
        return _SPA_SHELL_HTML

    # DOMAIN-APP-TOOLS-START — replace placeholder tools with domain logic.
    # Each app-only tool must use:
    #   meta=_app_tool_meta("<name>")
    #   app=AppConfig(resource_uri=_APP_URI, visibility=["app"])
    # Kept across copier update.

    # -- Primary tool: browse_vault -----------------------------------------

    @mcp.tool(
        tags={"apps-ui"},
        icons=_TOOL_ICONS["browse_vault"],
        annotations={
            "title": "Browse Vault",
            "readOnlyHint": True,
            "destructiveHint": False,
            "idempotentHint": True,
        },
        app=AppConfig(resource_uri=_APP_URI),
    )
    async def browse_vault(
        path: str | None = None,
        view: Literal["context", "graph", "browse", "note"] | None = None,
        vault: Vault = Depends(get_vault),
    ) -> dict[str, Any]:
        """Open a visual vault explorer UI for the user — not for reading vault content.

        Displays an interactive visual panel (MCP Apps) to the **user** so they can
        browse the file tree, explore the link graph, or view a note's relationships.
        Do NOT call this to retrieve or inspect vault content programmatically — use
        ``search`` to find notes, ``read`` for note content, ``list_documents`` to
        enumerate files, and ``get_context`` for a note's relationships instead.

        Only call this when the user explicitly asks to open the visual vault browser
        or explorer (e.g. "show me the vault browser", "open the graph view").

        Args:
            path: Optional note path to focus on (e.g. ``"Journal/2024-01-15.md"``).
            view: Which view to open: ``"context"`` (note relationships),
                ``"graph"`` (link visualization), ``"browse"`` (file tree),
                or ``"note"`` (full note preview).
                Defaults to ``"context"`` if a path is given, ``"browse"`` otherwise.

        Returns:
            - path (str | None): The requested note path, or null if none given.
            - view (str): The active view ("context", "graph", "browse", or "note").
            - summary (str): Text summary of vault or note state for non-Apps clients.
        """
        effective_view = view or ("context" if path else "browse")
        summary_parts: list[str] = []

        if path:
            meta = await asyncio.to_thread(vault.reader.get_metadata, path)
            if meta:
                summary_parts.append(f"Note: {meta.title} ({path})")
                summary_parts.append(f"Folder: {meta.folder}")
                if meta.frontmatter:
                    fm_keys = ", ".join(meta.frontmatter.keys())
                    summary_parts.append(f"Frontmatter: {fm_keys}")
            else:
                summary_parts.append(f"Note not found: {path}")
        else:
            stats = await asyncio.to_thread(vault.reader.stats)
            summary_parts.append(
                f"Vault: {stats.document_count} notes, {stats.folder_count} folders"
            )
            if stats.semantic_search_available:
                summary_parts.append("Semantic search: available")

        return {
            "path": path,
            "view": effective_view,
            "summary": "\n".join(summary_parts),
        }

    # -- App-only tools (hidden from LLM, used by SPA via callServerTool) ---

    @mcp.tool(
        icons=_TOOL_ICONS["vault_context"],
        annotations={
            "title": "Vault Context",
            "readOnlyHint": True,
            "destructiveHint": False,
            "idempotentHint": True,
            "openWorldHint": False,
        },
        meta=_app_tool_meta("vault_context"),
        app=AppConfig(resource_uri=_APP_URI, visibility=["app"]),
    )
    async def vault_context(
        path: str,
        vault: Vault = Depends(get_vault),
    ) -> dict[str, Any]:
        """Return the full NoteContext for a note (app-only).

        Called by the SPA context card view via ``app.callServerTool()``.
        Not visible to the LLM.

        Args:
            path: Relative note path (e.g. ``"Journal/2024-01-15.md"``).

        Returns:
            Dict with path, title, folder, frontmatter, modified_at, backlinks,
            outlinks, similar, folder_notes, and tags — see 'get_context' for
            field details. Returns {"error": "..."} if the note is not found.
        """
        try:
            ctx = await asyncio.to_thread(vault.reader.get_context, path)
        except ValueError:
            return {"error": f"Note not found: {path}"}
        return asdict(ctx)

    @mcp.tool(
        tags={"apps-ui"},
        icons=_TOOL_ICONS["show_context"],
        annotations={
            "title": "Context Card",
            "readOnlyHint": True,
            "destructiveHint": False,
            "idempotentHint": True,
        },
        app=AppConfig(resource_uri=_APP_URI),
    )
    async def show_context(
        path: str,
        vault: Vault = Depends(get_vault),
    ) -> dict[str, Any]:
        """Open a visual context card UI for the user — not for reading note relationships.

        Displays an interactive context panel (MCP Apps) to the **user** showing a
        note's backlinks, outlinks, similar notes, tags, and frontmatter visually.
        Do NOT call this to retrieve note relationship data programmatically — use
        ``get_context`` instead, which returns the full structured data.

        Only call this when the user explicitly asks to open the visual context card
        or explorer (e.g. "show me the context card for this note").

        Args:
            path: Relative note path (e.g. ``"Journal/2024-01-15.md"``).

        Returns:
            - path (str): The note path.
            - view (str): Always "context".
            - summary (str): Text summary with backlink, outlink, and similarity counts.
        """
        try:
            ctx = await asyncio.to_thread(vault.reader.get_context, path)
        except ValueError:
            return {
                "path": path,
                "view": "context",
                "summary": f"Note not found: {path}",
            }
        summary_parts = [
            f"Context for: {ctx.title} ({path})",
            f"Folder: {ctx.folder}",
            f"Backlinks: {len(ctx.backlinks)}",
            f"Outlinks: {len(ctx.outlinks)}",
            f"Similar notes: {len(ctx.similar)}",
            f"Folder peers: {len(ctx.folder_notes)}",
        ]
        if ctx.tags:
            tag_count = sum(len(v) for v in ctx.tags.values())
            summary_parts.append(f"Tags: {tag_count} across {len(ctx.tags)} fields")

        return {
            "path": path,
            "view": "context",
            "summary": "\n".join(summary_parts),
        }

    @mcp.tool(
        icons=_TOOL_ICONS["vault_graph_neighborhood"],
        annotations={
            "title": "Graph Neighborhood",
            "readOnlyHint": True,
            "destructiveHint": False,
            "idempotentHint": True,
            "openWorldHint": False,
        },
        meta=_app_tool_meta("vault_graph_neighborhood"),
        app=AppConfig(resource_uri=_APP_URI, visibility=["app"]),
    )
    async def vault_graph_neighborhood(
        path: str,
        depth: int = 1,
        include_semantic: bool = False,
        max_nodes: int = 200,
        vault: Vault = Depends(get_vault),
    ) -> dict[str, Any]:
        """Return the link neighborhood of a note as a node/edge graph (app-only).

        Called by the SPA graph view via ``app.callServerTool()``.
        Not visible to the LLM.

        Args:
            path: Center note path.
            depth: How many hops to traverse (default 1).
            include_semantic: When True, add dashed semantic-similarity edges
                for each interior node (requires embeddings to be configured;
                silently omitted when unavailable).
            max_nodes: Soft cap on returned node count (default 200). BFS
                and any semantic expansion both stop once the cap is hit;
                the response sets ``truncated=True``. Bounds dense-vault
                depth=2 traversals that would otherwise bog down vis-network.

        Returns:
            Dict with:

            - nodes (list): List of dicts, each with:

              - id (str): Unique identifier for the node.
              - label (str): Display name for the node.
              - group (str): "note" or "orphan".
              - folder (str): Parent folder path.
              - backlink_count (int): Number of inbound links.
              - note_type (str, optional): The note's OKF ``type``
                frontmatter value; present only on an active OKF
                bundle for notes that declare one.

            - edges (list): List of dicts, each with:

              - from (str): Source node ID.
              - to (str): Target node ID.
              - type (str): "markdown", "wikilink", "reference", or "semantic".

            - truncated (bool): True when BFS hit the ``max_nodes`` cap.
        """
        view = await asyncio.to_thread(
            vault.graph.get_neighborhood,
            path,
            depth=depth,
            include_semantic=include_semantic,
            max_nodes=max_nodes,
        )
        return _graph_view_payload(view, include_truncated=True)

    @mcp.tool(
        icons=_TOOL_ICONS["vault_graph_hubs"],
        annotations={
            "title": "Graph Hubs",
            "readOnlyHint": True,
            "destructiveHint": False,
            "idempotentHint": True,
            "openWorldHint": False,
        },
        meta=_app_tool_meta("vault_graph_hubs"),
        app=AppConfig(resource_uri=_APP_URI, visibility=["app"]),
    )
    async def vault_graph_hubs(
        limit: int = 20,
        vault: Vault = Depends(get_vault),
    ) -> dict[str, Any]:
        """Return the most-linked notes and their connections as a graph (app-only).

        Called by the SPA graph view for the hub overview.
        Not visible to the LLM.

        Args:
            limit: Max number of hub notes to include.

        Returns:
            Dict with:

            - nodes (list): List of dicts, each with:

              - id (str): Unique identifier for the node.
              - label (str): Display name for the node.
              - group (str): "hub" or "note".
              - folder (str): Parent folder path.
              - backlink_count (int): Number of inbound links.
              - note_type (str, optional): The note's OKF ``type``
                frontmatter value; present only on an active OKF
                bundle for notes that declare one.

            - edges (list): List of dicts, each with:

              - from (str): Source node ID.
              - to (str): Target node ID.
              - type (str): "markdown", "wikilink", or "reference".
        """
        view = await asyncio.to_thread(vault.graph.get_hub_graph, limit=limit)
        return _graph_view_payload(view, include_truncated=False)

    @mcp.tool(
        icons=_TOOL_ICONS["vault_list"],
        annotations={
            "title": "Vault List",
            "readOnlyHint": True,
            "destructiveHint": False,
            "idempotentHint": True,
            "openWorldHint": False,
        },
        meta=_app_tool_meta("vault_list"),
        app=AppConfig(resource_uri=_APP_URI, visibility=["app"]),
    )
    async def vault_list(
        folder: str | None = None,
        vault: Vault = Depends(get_vault),
    ) -> dict[str, Any]:
        """List folders and notes in a vault directory (app-only).

        Called by the SPA browser view via ``app.callServerTool()``.
        Not visible to the LLM.

        Args:
            folder: Folder to list (root if omitted).

        Returns:
            Dict with:

            - folders (list[str]): Direct child folder paths.
            - notes (list): Notes directly inside this folder. List of dicts,
              each with:

              - path (str): Relative path of the note.
              - title (str): Document title.
              - kind (str): "note" or "attachment".
        """
        docs = await asyncio.to_thread(
            vault.reader.list_documents, folder=folder, include_attachments=True
        )
        folders = await asyncio.to_thread(vault.reader.list_folders)

        # Build direct children: extract the first path component after the
        # prefix from every folder that lives under it.  This handles vaults
        # where list_folders() returns only leaf paths (e.g. "AI/LLM Tooling"
        # not "AI"), so top-level directories like "AI" still appear.
        prefix = (folder.rstrip("/") + "/") if folder else ""
        child_folders = sorted(
            {
                prefix + f[len(prefix) :].split("/")[0]
                for f in folders
                if f and f.startswith(prefix) and f != (folder or "")
            }
        )

        # Only return notes directly inside this folder (not nested ones)
        target_folder = folder or ""
        notes = [
            {
                "path": d.path,
                "title": getattr(d, "title", d.path.rsplit("/", 1)[-1]),
                "kind": d.kind,
            }
            for d in docs
            if d.folder == target_folder
        ]

        return {"folders": child_folders, "notes": notes}

    @mcp.tool(
        icons=_TOOL_ICONS["vault_read"],
        annotations={
            "title": "Vault Read",
            "readOnlyHint": True,
            "destructiveHint": False,
            "idempotentHint": True,
            "openWorldHint": False,
        },
        meta=_app_tool_meta("vault_read"),
        app=AppConfig(resource_uri=_APP_URI, visibility=["app"]),
    )
    async def vault_read(
        path: str,
        vault: Vault = Depends(get_vault),
    ) -> dict[str, Any] | None:
        """Read a note's full content for preview rendering (app-only).

        Called by the SPA browser view via ``app.callServerTool()``.
        Not visible to the LLM.

        Args:
            path: Relative note path.

        Returns:
            Dict with path, title, frontmatter, content (the full raw file,
            including the frontmatter block), and modified_at (Unix timestamp),
            or null if the note is not found.
        """
        note = await asyncio.to_thread(vault.reader.read, path)
        if note is None:
            return None
        return {
            "path": note.path,
            "title": note.title,
            "frontmatter": note.frontmatter,
            "content": note.content,
            "modified_at": note.modified_at,
        }

    @mcp.tool(
        icons=_TOOL_ICONS["vault_search"],
        annotations={
            "title": "Vault Search",
            "readOnlyHint": True,
            "destructiveHint": False,
            "idempotentHint": True,
            "openWorldHint": False,
        },
        meta=_app_tool_meta("vault_search"),
        app=AppConfig(resource_uri=_APP_URI, visibility=["app"]),
    )
    async def vault_search(
        query: str,
        mode: Literal["keyword", "semantic", "hybrid"] = "hybrid",
        limit: int = 20,
        vault: Vault = Depends(get_vault),
    ) -> list[dict[str, Any]]:
        """Search the vault (app-only).

        Called by the SPA browser search bar via ``app.callServerTool()``.
        Not visible to the LLM.

        Args:
            query: Search query string.
            mode: Search mode (keyword, semantic, or hybrid).
            limit: Max results.

        Returns:
            List of result dicts, each with path (str), title (str),
            snippet (str, first 200 chars of matched chunk), and
            score (float). Returns [{"error": "..."}] on search failure.
        """
        try:
            results = await asyncio.to_thread(
                vault.reader.search, query, limit=limit, mode=mode
            )
        except ValueError as exc:
            return [{"error": str(exc)}]
        # GroupedResult.sections is non-empty for any hit returned by
        # SearchManager.search; pull the snippet from the top section.
        # The SPA browser view consumes a flat {path, title, snippet,
        # score} shape — surfacing only the best section keeps the
        # payload small and matches the pre-collapse rendering.
        return [
            {
                "path": r.path,
                "title": r.title,
                "snippet": (
                    r.sections[0].content[:200]
                    if r.sections and r.sections[0].content
                    else ""
                ),
                "score": r.score,
            }
            for r in results
        ]

    # DOMAIN-APP-TOOLS-END
