"""MCP Apps scaffold for Markdown Vault MCP.

Demonstrates the fastmcp app-tool addressing pattern (>=3.2.4; the project pins >=4):

- Hash injection via ``hash_tool`` / ``hashed_backend_name`` from
  ``fastmcp.server.providers.addressing``.
- ``_rewrite_spa_app_tool_calls``: validates and rewrites
  ``app___<tool>`` source literals in the SPA HTML to the
  ``<hex_hash>_<tool>`` wire form at module import.
- ``_APP_TOOL_NAMES``: single source of truth for app-only tool names;
  three-way validation rejects drift between the set, the HTML, and the
  registration sites.

Replace the placeholder tools and HTML with your domain's implementation.
See ``register_apps`` for the tool registration pattern (``DOMAIN-APP-TOOLS``),
the ``DOMAIN-APP-RESOURCE`` block to configure the app-shell resource's
``AppConfig`` (e.g. sandbox ``domain`` + ``csp`` for a UI loaded in a client's
sandboxed iframe), and ``_SPA_SHELL_HTML`` (loaded from ``static/app.html``,
generated by ``scripts/vendor_spa.py`` from ``static/app.src.html``).
"""

from __future__ import annotations

import importlib.resources
import logging
import re
from typing import Any

from fastmcp import FastMCP
from fastmcp_pvl_core import tool_boundary

try:
    from fastmcp.apps import AppConfig
    from fastmcp.server.providers.addressing import (
        TOOL_HASH_META_KEY,
        hash_tool,
        hashed_backend_name,
    )
except ImportError as exc:  # pragma: no cover
    raise ImportError(
        "fastmcp.apps and fastmcp.server.providers.addressing are required "
        "for MCP Apps SPA tool routing. Pin fastmcp>=4 in pyproject.toml."
    ) from exc

logger = logging.getLogger(__name__)

_APP_NAME = "markdown_vault_mcp"
_APP_URI = "ui://markdown_vault_mcp/app.html"

# Single source of truth for app-only tool names.
# Three invariants are enforced automatically:
#   (1) _rewrite_spa_app_tool_calls at module import rejects HTML with zero
#       app___<name> literals.
#   (2) _rewrite_spa_app_tool_calls rejects literals not in this set.
#   (3) _rewrite_spa_app_tool_calls rejects names in this set absent from HTML.
# _app_tool_meta enforces (2) again at register_apps() call time.
# When adding a tool: add its name here AND add a matching
# app___<name> literal to the SPA HTML in static/app.src.html.
_APP_TOOL_NAMES: frozenset[str] = frozenset(
    {
        # DOMAIN-APP-TOOL-NAMES-START — add app-only tool names here; kept across copier update.
        "vault_context",
        "vault_graph_neighborhood",
        "vault_graph_hubs",
        "vault_list",
        "vault_read",
        "vault_search",
        # DOMAIN-APP-TOOL-NAMES-END
    }
)


def _app_tool_meta(tool_name: str) -> dict[str, Any]:
    """Build the per-tool ``meta`` dict for a post-3.2.4 app-only tool.

    The hash goes under fastmcp's public ``TOOL_HASH_META_KEY``
    (``"tool_hash"``), the key ``get_tool_by_hash`` reads. An
    underscore-prefixed key looks the same in-process but is stripped from
    ``meta["fastmcp"]`` when the tool is serialised for the protocol, so a
    client never saw the hash (#614).
    """
    if tool_name not in _APP_TOOL_NAMES:
        raise ValueError(f"Unknown app tool {tool_name!r}; add to _APP_TOOL_NAMES.")
    return {
        "fastmcp": {
            "app": _APP_NAME,
            TOOL_HASH_META_KEY: hash_tool(_APP_NAME, tool_name),
        }
    }


def _hashed(tool_name: str) -> str:
    """Return the ``<hash>_<tool_name>`` callable name for an app-only tool."""
    return hashed_backend_name(_APP_NAME, tool_name)


def _rewrite_spa_app_tool_calls(html: str) -> str:
    """Rewrite SPA's ``app___<tool>`` literals to fastmcp's hash form.

    fastmcp 3.2.4 dropped ``<app>___<tool>`` routing; the dispatcher now
    only accepts ``<hex_hash>_<tool>`` (computed by
    :func:`fastmcp.server.providers.addressing.hashed_backend_name`).
    Substitution happens once at module import so the source HTML stays
    diff-readable while the wire form is already addressed correctly.

    Raises :class:`RuntimeError` if:

    - zero ``app___<tool>`` literals are found in the HTML;
    - the HTML references a tool name not in :data:`_APP_TOOL_NAMES`;
    - :data:`_APP_TOOL_NAMES` contains a name absent from the HTML.
    """
    captured: set[str] = set()

    def _capture(m: re.Match[str]) -> str:
        name = m.group(1)
        captured.add(name)
        return _hashed(name)

    new_html, count = re.subn(
        r"app___([a-z_][a-z0-9_]*)",
        _capture,
        html,
    )
    if count == 0:
        raise RuntimeError(
            "SPA rewrite found zero 'app___<tool>' literals — "
            "check static/app.html still uses the app___<tool> source form."
        )
    unexpected = captured - _APP_TOOL_NAMES
    if unexpected:
        raise RuntimeError(
            f"SPA references unknown tools: {sorted(unexpected)}. "
            "Fix the typo in static/app.src.html or add the name to _APP_TOOL_NAMES."
        )
    missing = _APP_TOOL_NAMES - captured
    if missing:
        raise RuntimeError(
            f"SPA doesn't reference declared tools: {sorted(missing)}. "
            "Remove from _APP_TOOL_NAMES or wire the SPA to call them."
        )
    return new_html


# SPA shell HTML — loaded from the vendored static/app.html (generated by
# scripts/vendor_spa.py).  Uses fixed app___<tool> source literals;
# _rewrite_spa_app_tool_calls rewrites them to fastmcp's post-3.2.4 hash form
# at module import.  Edit static/app.src.html (not app.html) and re-run
# scripts/vendor_spa.py.
_SPA_SHELL_HTML = _rewrite_spa_app_tool_calls(
    importlib.resources.files("markdown_vault_mcp")
    .joinpath("static/app.html")
    .read_text(encoding="utf-8")
)


def register_apps(mcp: FastMCP) -> None:
    """Register MCP Apps resource and app-only tools on *mcp*."""

    # DOMAIN-APP-RESOURCE-START — configure the app-shell resource's ``AppConfig``:
    # e.g. ``domain=<sandbox host>`` and ``csp=ResourceCSP(...)`` for a UI a client
    # loads in a sandboxed iframe. Leave ``None`` for a plain resource with no
    # domain/CSP. Domains that need to resolve the value (env, hashing, etc.) can
    # do so here or import a helper. Kept across copier update.
    from markdown_vault_mcp._vault_apps import vault_app_resource_config

    app_resource_config: AppConfig | None = vault_app_resource_config()
    # DOMAIN-APP-RESOURCE-END

    @mcp.resource(_APP_URI, app=app_resource_config)
    def _app_shell() -> str:
        return _SPA_SHELL_HTML

    # DOMAIN-APP-TOOLS-START — replace placeholder tools with domain logic.
    # Each app-only tool must use:
    #   meta=_app_tool_meta("<name>")
    #   app=AppConfig(resource_uri=_APP_URI, visibility=["app"])
    # and ``@tool_boundary`` under ``@mcp.tool``, like every other tool.
    # Kept across copier update.
    #
    # The vault's tools replace the placeholders; they live in _vault_app_tools.py
    # so this block keeps the template's text above.
    from markdown_vault_mcp._vault_app_tools import register_vault_app_tools

    register_vault_app_tools(mcp, _APP_URI, _app_tool_meta)

    # DOMAIN-APP-TOOLS-END
