"""Vault-backed transfer hooks for pvl-core's capability-link routes (#979).

``fastmcp_pvl_core.register_transfer_routes`` owns the token store, the
``/transfer/{token}`` route, the generic ``create_download_link`` /
``create_upload_link`` tools (with their titles, hints, and icons), and all
size-cap / TTL mechanics. This module supplies the one domain hook it consumes:
a :class:`~fastmcp_pvl_core.TransferSink` (where bytes come from / go to) plus a
``TransferValidator`` (which refs are acceptable):

- **download** — ``read`` serves an existing vault note or attachment's bytes.
- **upload** — ``write`` commits uploaded bytes to a validated destination path
  through the normal write path.

The sink is byte-oriented (pvl-core materialises the whole body, bounded by the
per-upload cap); it never interprets the ``/transfer`` route or the token store.
Path validation runs at link-creation time in :meth:`VaultTransferSink.validate`
(the ``TransferValidator``), so a bad ref is rejected before a token is minted.
A rejection is a ``ToolError`` at INFO telling the model what to pass instead;
anything else the hook raises is a server fault (#1623).
The upstream error and retry contract is recorded in
``docs/design/reference/fastmcp-transfer.md``.
"""

from __future__ import annotations

import asyncio
import base64
import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any

from fastmcp.exceptions import ToolError
from fastmcp_pvl_core import (
    TransferReadResult,
    TransferResourceGoneError,
    TransferSinkError,
    TransferUnavailableError,
)

from markdown_vault_mcp.domain import get_vault_singleton
from markdown_vault_mcp.exceptions import DocumentExistsError, DocumentNotFoundError
from markdown_vault_mcp.okf_bundle import build_okf_bundle
from markdown_vault_mcp.utils import (
    artifact_suffix,
    effective_attachment_extensions,
    is_allowed_artifact_suffix,
    is_note,
    resolve_inside,
    validate_path,
)
from markdown_vault_mcp.utils.fs import is_directory, is_regular_file
from markdown_vault_mcp.utils.text import decode_utf8

logger = logging.getLogger(__name__)

if TYPE_CHECKING:
    from collections.abc import Callable, Mapping, Sequence

    from fastmcp_pvl_core import TransferKind

    from markdown_vault_mcp.config import ProjectConfig
    from markdown_vault_mcp.vault import Vault

_MARKDOWN_MEDIA_TYPE = "text/markdown; charset=utf-8"
_OCTET_STREAM = "application/octet-stream"
_ZIP_MEDIA_TYPE = "application/zip"

# Download-ref scheme that delivers a generated OKF bundle rather than an
# existing vault file (#963). ``okf-bundle`` exports the whole vault;
# ``okf-bundle:<folder>`` scopes to a subtree. The domain sink recognises it —
# pvl-core's create_download_link serves the generated bytes unchanged.
_OKF_BUNDLE_REF = "okf-bundle"


def _reject(message: str) -> ToolError:
    """Build a rejection of a link ref that the model acts on (#1623).

    pvl-core's validate-hook contract: a ref is rejected with a ``ToolError``
    at INFO, whose message the model reads; any other exception is a server
    fault.
    """
    return ToolError(message, log_level=logging.INFO)


_VAULT_PATH_HINT = "Pass a path relative to the vault root."
_BUNDLE_FOLDER_HINT = (
    "Pass a folder that list_folders returns, or okf-bundle for the whole vault."
)


def _inside(
    path: str, source_dir: Path, *, note: bool, hint: str = _VAULT_PATH_HINT
) -> Path:
    """Resolve *path* inside the vault, rejecting an escape as the caller's to fix."""
    try:
        if note:
            return validate_path(path, source_dir)
        return resolve_inside(path, source_dir)
    except ValueError as exc:
        raise _reject(f"{exc}. {hint}") from None


def _extension_rejected(ext: str) -> ToolError:
    """Reject an attachment extension the vault does not allow."""
    # The operator's setting goes in the log, not the model's text (#1639).
    logger.info(
        "transfer_refused_extension extension=%s setting=%s",
        ext,
        "MARKDOWN_VAULT_MCP_ATTACHMENT_EXTENSIONS",
    )
    return _reject(
        f"Attachment extension not allowed: .{ext}. Use a note (.md) or an "
        "extension listed in stats' attachment_extensions."
    )


def _bundle_scope(ref: str) -> str | None:
    """Return the folder scope if *ref* is an OKF-bundle ref, else ``None``.

    ``""`` means the whole vault; a non-empty string is a folder subtree.
    ``None`` means *ref* is an ordinary vault path, not a bundle ref.
    """
    if ref == _OKF_BUNDLE_REF:
        return ""
    prefix = f"{_OKF_BUNDLE_REF}:"
    if ref.startswith(prefix):
        return ref[len(prefix) :].strip("/")
    return None


def _validate_destination(
    path: str,
    source_dir: Path,
    attachment_extensions: Sequence[str] | None,
) -> Path:
    """Validate an upload destination path (a note or an allowed attachment).

    Args:
        path: Vault-relative destination path.
        source_dir: Vault root.
        attachment_extensions: Configured allowlist (``None`` = defaults).

    Returns:
        The validated absolute destination path.

    Raises:
        ToolError: At INFO, on path traversal or a disallowed attachment
            extension.
    """
    if is_note(path):
        return _inside(path, source_dir, note=True)
    resolved = _inside(path, source_dir, note=False)
    exts = effective_attachment_extensions(attachment_extensions)
    ext = artifact_suffix(resolved)
    if not is_allowed_artifact_suffix(ext, exts):
        raise _extension_rejected(ext)
    return resolved


def _validate_source(
    path: str,
    source_dir: Path,
    attachment_extensions: Sequence[str] | None,
) -> None:
    """Validate a download source path (stat-only — never reads the file).

    Verifies existence without reading, so minting a download link for a large
    attachment never loads it into memory.

    Args:
        path: Vault-relative source path.
        source_dir: Vault root.
        attachment_extensions: Configured allowlist (``None`` = defaults).

    Raises:
        ToolError: At INFO, on path traversal, a missing file, or a
            disallowed attachment extension.
        OSError: When the file cannot be checked. That is the server's
            fault, not the ref's, so it is not a rejection.
    """
    is_artifact = not is_note(path)
    resolved = _inside(path, source_dir, note=not is_artifact)
    if not is_regular_file(resolved):
        listing = (
            "list_documents(include_attachments=True)"
            if is_artifact
            else "search or list_documents"
        )
        kind = "Attachment" if is_artifact else "Note"
        raise _reject(f"{kind} not found: {path}. Look the path up with {listing}.")
    if is_artifact:
        exts = effective_attachment_extensions(attachment_extensions)
        ext = artifact_suffix(resolved)
        if not is_allowed_artifact_suffix(ext, exts):
            raise _extension_rejected(ext)


class VaultTransferSink:
    """:class:`TransferSink` + validator backed by the vault.

    The live :class:`~markdown_vault_mcp.vault.Vault` is resolved per request
    (it is created by the server lifespan), so a single sink instance can be
    wired at server-build time. The opaque ``sink_handle`` is simply the
    vault-relative path; :meth:`read` / :meth:`write` re-derive note-vs-attachment
    from the ``.md`` suffix.
    """

    def __init__(
        self,
        config: ProjectConfig,
        vault_provider: Callable[[], Vault] = get_vault_singleton,
    ) -> None:
        """Hold the config (for path validation) and a live-vault resolver.

        Args:
            config: The loaded project config — supplies the vault root and the
                attachment-extension allowlist for validation.
            vault_provider: Resolves the live vault at request time (defaults to
                the module singleton; injectable for tests).
        """
        self._config = config
        self._vault = vault_provider

    async def validate(self, ref: str, kind: TransferKind) -> str:
        """Validate a link ref; return the opaque sink handle or raise to reject.

        The handle is the vault-relative path itself. Download validation is
        stat-only (existence without a read); upload validation checks the
        destination is a note or an allowed attachment, and rejects existing
        files when overwrite protection is enabled. ``kind`` selects which.

        Args:
            ref: Vault-relative path of a note or attachment.
            kind: ``"download"`` or ``"upload"``.

        Returns:
            The vault-relative path (or the ``okf-bundle`` ref verbatim), stored
            as the sink handle.

        Raises:
            ToolError: At INFO, rejecting the ref: path traversal, a missing
                download source, a disallowed attachment extension, a bundle
                ref with OKF disabled, a bundle scope naming a folder that does
                not exist, or an existing upload destination when overwrite
                protection is enabled.
            ConfigurationError: When the lifespan built no vault (the
                configured directory does not exist): a link must not be
                minted that can only fail when followed.
        """
        self._vault()  # refuse to mint against a vault that is not there
        source_dir = self._config.source_dir
        exts = self._config.content.attachment_extensions
        if kind == "download":
            scope = _bundle_scope(ref)
            if scope is not None:
                self._validate_bundle_scope(scope)
                return ref
            _validate_source(ref, source_dir, exts)
        else:
            destination = _validate_destination(ref, source_dir, exts)
            if self._config.write_protect_existing and is_regular_file(destination):
                logger.info(
                    "transfer_upload_refused_protected ref=%s setting=%s",
                    ref,
                    "MARKDOWN_VAULT_MCP_WRITE_PROTECT_EXISTING",
                )
                raise _reject(
                    f"{ref} exists; upload links require a new path while this "
                    "vault protects existing files from blind overwrites. "
                    "Choose a new path."
                )
        return ref

    def _validate_bundle_scope(self, scope: str) -> None:
        """Validate an OKF-bundle download scope at link-creation time.

        Args:
            scope: ``""`` for the whole vault, else a folder subtree.

        Raises:
            ToolError: At INFO, if OKF is disabled (``OKF_MODE=off``), the
                scope escapes the vault, or names a folder that does not exist.
        """
        if self._config.content.okf_mode == "off":
            logger.info(
                "transfer_refused_bundle reason=okf_off setting=%s",
                "MARKDOWN_VAULT_MCP_OKF_MODE",
            )
            raise _reject(
                "OKF bundle export is not enabled on this server. Download "
                "individual notes instead."
            )
        if not scope:
            return
        folder = _inside(
            scope, self._config.source_dir, note=False, hint=_BUNDLE_FOLDER_HINT
        )
        if not is_directory(folder):
            raise _reject(f"Bundle folder not found: {scope}. {_BUNDLE_FOLDER_HINT}")

    def _resolve_vault(self) -> Vault:
        """Resolve the live vault, or signal a retryable 503 if it is torn down.

        The vault singleton is owned by a ref-counted session lifespan and is
        cleared when all MCP sessions close, while the ``/transfer/{token}``
        route stays mounted for the server's lifetime. A link followed in that
        window would otherwise raise a bare ``RuntimeError`` and surface as a
        generic 500; mapping it to :class:`~fastmcp_pvl_core.TransferUnavailableError`
        gives the caller a clean, retryable **503** instead (the route releases
        the token, so the link survives the retry). See fastmcp-pvl-core#233.

        Raises:
            TransferUnavailableError: If the vault is not currently available.
        """
        try:
            return self._vault()
        except RuntimeError as exc:
            logger.warning(
                "transfer_vault_unavailable error_type=%s", type(exc).__name__
            )
            raise TransferUnavailableError(
                "vault is not currently available; retry shortly"
            ) from exc

    async def read(self, handle: str) -> TransferReadResult:
        """Serve a vault note or attachment's bytes for a download handle.

        Args:
            handle: The vault-relative path the link was minted with.

        Returns:
            A :class:`~fastmcp_pvl_core.TransferReadResult` — bytes, media type,
            and download filename.

        Raises:
            TransferUnavailableError: The vault is being torn down (retryable 503).
            TransferResourceGoneError: The note/attachment existed at mint time
                but has since been removed (410 Gone).
        """
        scope = _bundle_scope(handle)
        if scope is not None:
            return await self._read_bundle(scope)
        vault = self._resolve_vault()
        filename = Path(handle).name
        if is_note(handle):
            note = await asyncio.to_thread(vault.reader.read, handle)
            if note is None:
                logger.warning("transfer_download_note_gone path=%s", handle)
                raise TransferResourceGoneError(f"note no longer available: {handle}")
            body = note.content.encode("utf-8")
            logger.info("transfer_download_served path=%s bytes=%d", handle, len(body))
            return TransferReadResult(body, _MARKDOWN_MEDIA_TYPE, filename)
        try:
            att = await asyncio.to_thread(vault.reader.read_attachment, handle)
        except DocumentNotFoundError as exc:
            # The file is gone; validate confirmed it at mint time, so this is a
            # 410 Gone, not a 500. A refused read is a plain ValueError and
            # propagates as the server's failure, never as absence (#1608).
            logger.warning("transfer_download_attachment_gone path=%s", handle)
            raise TransferResourceGoneError(
                f"attachment no longer available: {handle}"
            ) from exc
        body = base64.b64decode(att.content_base64)
        media_type = att.mime_type or _OCTET_STREAM
        logger.info("transfer_download_served path=%s bytes=%d", handle, len(body))
        return TransferReadResult(body, media_type, filename)

    async def _read_bundle(self, scope: str) -> TransferReadResult:
        """Generate and serve an OKF bundle zip for a bundle-ref download.

        The bundle is built from live vault state (never mutating it); a large
        vault runs off the event loop via :func:`asyncio.to_thread`.

        Args:
            scope: ``""`` for the whole vault, else a folder subtree.

        Returns:
            A :class:`~fastmcp_pvl_core.TransferReadResult` carrying the zip.

        Raises:
            TransferUnavailableError: The vault is being torn down (retryable 503).
            TransferResourceGoneError: A folder scope validated at mint time has
                since been removed (410 Gone), mirroring the single-file path
                rather than serving an empty archive.
        """
        vault = self._resolve_vault()
        if scope and not is_directory((self._config.source_dir / scope).resolve()):
            logger.warning("transfer_download_bundle_folder_gone scope=%s", scope)
            raise TransferResourceGoneError(
                f"bundle folder no longer available: {scope}"
            )
        result = await asyncio.to_thread(
            build_okf_bundle, vault, self._config, folder=scope
        )
        stem = scope.rsplit("/", 1)[-1] if scope else _OKF_BUNDLE_REF
        logger.info(
            "transfer_download_bundle scope=%s notes=%d attachments=%d bytes=%d",
            scope or "(root)",
            result.notes,
            result.attachments,
            len(result.data),
        )
        return TransferReadResult(result.data, _ZIP_MEDIA_TYPE, f"{stem}.zip")

    async def write(self, handle: str, body: bytes) -> Mapping[str, Any]:
        """Commit an uploaded body to a vault note or attachment path.

        Args:
            handle: The vault-relative destination path.
            body: The uploaded bytes (already size-capped by the route).

        Returns:
            A payload dict with the written ``path`` and ``bytes``.

        Raises:
            TransferUnavailableError: The vault is being torn down (retryable 503).
            UnicodeDecodeError: A note upload whose body is not valid UTF-8.
            TransferSinkError: The protected destination exists, including a
                file created after validation or by a prior upload (409 Conflict).
        """
        vault = self._resolve_vault()
        try:
            if is_note(handle):
                text = decode_utf8(body)  # strips a leading BOM (#681)
                await asyncio.to_thread(vault.writer.write, handle, text)
            else:
                await asyncio.to_thread(vault.writer.write_attachment, handle, body)
        except DocumentExistsError as exc:
            raise TransferSinkError(
                409, f"upload destination exists: {handle}"
            ) from exc
        logger.info("transfer_upload_committed path=%s bytes=%d", handle, len(body))
        return {"path": handle, "bytes": len(body)}
